# Generated by Django 5.1.3 on 2024-12-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='action',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
