# Generated by Django 5.1.3 on 2024-12-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_diaryentry_user_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
